spring:
  application:
    name: supplier-service
  datasource:
    driver-class-name:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
  jpa:
    generate-ddl: true
    show-sql:  true

server:
  port: 8081
