INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('ООО РемТех', 'Иван Иванов', '+7-900-111-2222', 'ivanov@remtech.ru', 'г. Москва, ул. Ленина, д.1');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('СнабТорг', 'Петр Петров', '+7-900-333-4444', 'petrov@snabtor.ru', 'г. Санкт-Петербург, пр. Невский, д.12');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('ТехноПоставка', 'Сергей Сергеев', '+7-900-555-6666', 'sergeev@technopostavka.ru', 'г. Новосибирск, ул. Советская, д.34');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('КомплектМаркет', 'Анна Смирнова', '+7-900-777-8888', 'smirnova@komplektmarket.ru', 'г. Екатеринбург, ул. Мира, д.7');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('ПрофиДистрибуция', 'Олег Кузнецов', '+7-900-999-0000', 'kuznetsov@profidist.ru', 'г. Казань, ул. Пушкина, д.45');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('ТехМир', 'Марина Ковалёва', '+7-900-123-4567', 'kovaleva@tehmir.ru', 'г. Нижний Новгород, ул. Гагарина, д.2');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('РемСервис', 'Дмитрий Волков', '+7-900-234-5678', 'volkov@remservice.ru', 'г. Челябинск, ул. Победы, д.9');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('ПоставкаПлюс', 'Елена Зайцева', '+7-900-345-6789', 'zaitseva@postavkaplus.ru', 'г. Самара, ул. Московская, д.14');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('СервисКомплект', 'Алексей Соколов', '+7-900-456-7890', 'sokolov@servicekomplekt.ru', 'г. Омск, ул. Ленина, д.16');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('ТехноСнаб', 'Ольга Морозова', '+7-900-567-8901', 'morozova@technosnab.ru', 'г. Ростов-на-Дону, ул. Кирова, д.11');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('МегаКомплект', 'Виктор Смирнов', '+7-900-678-9012', 'smirnov@megakomplekt.ru', 'г. Уфа, ул. Лермонтова, д.5');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('ПрофТех', 'Наталья Кузнецова', '+7-900-789-0123', 'kuznetsova@profteh.ru', 'г. Волгоград, ул. Мира, д.8');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('РемКомплект', 'Андрей Попов', '+7-900-890-1234', 'popov@remkomplekt.ru', 'г. Пермь, ул. Комсомольская, д.4');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('ТехСнаб', 'Мария Иванова', '+7-900-901-2345', 'ivanova@tehsnab.ru', 'г. Красноярск, ул. Советская, д.3');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('ПоставкаСервис', 'Игорь Федоров', '+7-900-012-3456', 'fedorov@postavkaservice.ru', 'г. Воронеж, ул. Ленина, д.7');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('СнабРемонт', 'Татьяна Михайлова', '+7-900-123-4560', 'mihailova@snabremont.ru', 'г. Саратов, ул. Первомайская, д.12');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('ТехКомплект', 'Владимир Павлов', '+7-900-234-5671', 'pavlov@tehkomplekt.ru', 'г. Тюмень, ул. Гагарина, д.10');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('РемПро', 'Екатерина Васильева', '+7-900-345-6782', 'vasilieva@rempro.ru', 'г. Ижевск, ул. Пушкина, д.1');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('КомплектПрофи', 'Сергей Николаев', '+7-900-456-7893', 'nikolaev@komplektprofi.ru', 'г. Барнаул, ул. Ленина, д.13');
INSERT INTO supplier (name, contact_person, phone, email, address) VALUES ('ТехМастер', 'Людмила Орлова', '+7-900-567-8904', 'orlova@tehmaster.ru', 'г. Калининград, ул. Советская, д.6');
