INSERT INTO category (name, description) VALUES ('Принтеры', 'Ремонт и обслуживание принтеров');
INSERT INTO category (name, description) VALUES ('Сканеры', 'Ремонт сканеров и МФУ');
INSERT INTO category (name, description) VALUES ('Копировальные аппараты', 'Обслуживание копиров');
INSERT INTO category (name, description) VALUES ('Факсы', 'Ремонт факсимильных аппаратов');
INSERT INTO category (name, description) VALUES ('Картриджи', 'Заправка и восстановление картриджей');
INSERT INTO category (name, description) VALUES ('Компьютеры', 'Ремонт ПК');
INSERT INTO category (name, description) VALUES ('Ноутбуки', 'Диагностика и ремонт ноутбуков');
INSERT INTO category (name, description) VALUES ('Мониторы', 'Ремонт мониторов');
INSERT INTO category (name, description) VALUES ('Сетевое оборудование', 'Роутеры, свитчи и пр.');
INSERT INTO category (name, description) VALUES ('Программное обеспечение', 'Установка и обновление ПО');
INSERT INTO category (name, description) VALUES ('Периферия', 'Клавиатуры, мыши и пр.');
INSERT INTO category (name, description) VALUES ('Запасные части', 'Комплектующие для оргтехники');
INSERT INTO category (name, description) VALUES ('ИБП', 'Источники бесперебойного питания');
INSERT INTO category (name, description) VALUES ('Проекторы', 'Ремонт проекторов');
INSERT INTO category (name, description) VALUES ('Жесткие диски', 'HDD и SSD');
INSERT INTO category (name, description) VALUES ('Материнские платы', 'Ремонт и замена');
INSERT INTO category (name, description) VALUES ('Кабели и коннекторы', 'Сетевые и другие кабели');
INSERT INTO category (name, description) VALUES ('Аудио техника', 'Ремонт акустики');
INSERT INTO category (name, description) VALUES ('Гаджеты', 'Планшеты и смартфоны');
INSERT INTO category (name, description) VALUES ('Диагностика', 'Полная диагностика устройств');
