INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Тонер-картридж HP', 'Картридж для лазерного принтера HP', 5, 1, 2500.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Лазерный барабан Canon', 'Барабан для принтеров Canon', 5, 2, 3500.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Плата управления Epson', 'Плата для сканеров Epson', 2, 3, 4200.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Ролик подачи бумаги', 'Ролик для копировального аппарата', 3, 4, 1200.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Плата факса Panasonic', 'Плата для факсов Panasonic', 4, 5, 2800.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Жёсткий диск WD 1TB', 'Жесткий диск Western Digital', 15, 6, 4500.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Материнская плата Asus', 'Плата для ПК Asus', 16, 7, 7800.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Блок питания 500W', 'Блок питания для ПК', 12, 8, 3200.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Кабель HDMI 2м', 'Кабель HDMI высокого качества', 17, 9, 700.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Мышь беспроводная Logitech', 'Беспроводная мышь', 11, 10, 1500.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Проектор Epson X123', 'Лампа для проектора Epson', 14, 11, 9800.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('ИБП APC 600VA', 'Источник бесперебойного питания', 13, 12, 6300.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Монитор Samsung 24"', 'Монитор Samsung 24 дюйма', 8, 13, 11000.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Ноутбук Dell XPS', 'Ноутбук Dell для офисных задач', 7, 14, 55000.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Программное обеспечение MS Office', 'Лицензия Microsoft Office', 10, 15, 12000.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Сканер Canon Lide', 'Сканер Canon', 2, 16, 15000.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Клавиатура USB', 'Клавиатура с USB подключением', 11, 17, 1200.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Ремкомплект принтера', 'Набор запчастей для ремонта', 1, 18, 4500.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Сетевой роутер TP-Link', 'Роутер TP-Link', 9, 19, 4800.0);
INSERT INTO parts (name, description, category_id, supplier_id, unit_price) VALUES ('Акустическая система Logitech', 'Акустика для ПК', 18, 20, 7000.0);
