spring:
  sql:
    init:
      mode: always
  application:
    name: inventory-service

  profiles:
    active: test

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/xenon_diplom
    username: postgres
    password: pass

  jpa:
    generate-ddl: true
    show-sql: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
